name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/LuizAuto
            git stash
            git pull origin main
            npm install
            mkdir -p public/uploads/vehicles
            chmod -R 755 public/uploads
            chown -R www-data:www-data public/uploads
            pm2 restart luizauto || pm2 start server.js --name luizauto
            pm2 save 